### ISSUE TITLE
suggestion: add clicks all (raw + unique) column to Daily reports grid

### ISSUE THREAD

**Issue by lnikodem** [QualityUnit/pap-public#50] opened 2015-08-13 08:36 UTC
suggestion: add clicks all (raw + unique) column to Daily reports grid

**Comment by mkendera** [comment] 2015-08-13 09:04
@lnikodem odkial je to suggestion?
duplicate of: https://github.com/QualityUnit/pap-issues/issues/469

**Comment by mkendera** [comment] 2015-08-13 10:24
close: duplicate of: https://github.com/QualityUnit/pap-public/issues/49

**Closed by mkendera** 2015-08-13 10:24 UTC
